### ISSUE TITLE
New Code Causes Prompt to Blow Up

### ISSUE THREAD

**Issue by jkrot** [lyze/posh-git-sh#15] opened 2016-07-08 20:50 UTC
I am running this on a mac and using the new code my prompt looks like, going back a commit and it looks fine.
<img width="575" alt="screen shot 2016-07-08 at 3 49 48 pm" src="https://cloud.githubusercontent.com/assets/124587/16701172/ae369a6c-4523-11e6-939b-40e920437551.png">

**Comment by dmccaffery** [comment] 2016-07-09 01:30
Seconded. Definitely an issue on OS X currently.

**Comment by lyze** [comment] 2016-07-10 12:58
I won't have access to a Mac until tomorrow, so I can't debug the issue yet. In the meantime, what does the output look like if ANSI color interpretation is disabled in the terminal settings? I'm guessing this happens on the (old 3.x) bash that ships with OSX by default?

**Comment by dmccaffery** [comment] 2016-07-11 12:17
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

Thats the version of bash that I am using. It is quite old. I'll have to reinstall the latest bits and disable ANSI to get back to you re: what the output looks like without ANSI.

**Comment by dmccaffery** [comment] 2016-07-11 12:28
Before (ANSI):
<img width="509" alt="screen shot 2016-07-11 at 5 19 49 am" src="https://cloud.githubusercontent.com/assets/1803684/16730447/ea0c7592-4727-11e6-8061-1d098d1ba97d.png">
After (ANSI):
<img width="429" alt="screen shot 2016-07-11 at 5 25 16 am" src="https://cloud.githubusercontent.com/assets/1803684/16730452/f320be9a-4727-11e6-9ca1-7741106c619c.png">

ANSI disabled:
<img width="386" alt="screen shot 2016-07-11 at 5 26 31 am" src="https://cloud.githubusercontent.com/assets/1803684/16730481/0e65c272-4728-11e6-9d42-a30d626c356b.png">

Does not emit the ANSI color codes when disabling ANSI... OS X terminal just swallows them, it would appear. I tried changing the TERM as well to no effect.

The prompt is set using the following script (part of my prompt kit):
https://github.com/pulsebridge/uber/blob/master/src/scripts/set-prompt.sh

**Comment by lyze** [comment] 2016-07-11 13:19
I think 8d28204 should fix things. I promise I do know how to get a backslash to show up with `echo`... :crying_cat_face:

**Comment by dmccaffery** [comment] 2016-07-11 14:12
@lyze confirmed -- 8d28204 works for me. :shipit:

**Comment by dmccaffery** [comment] 2016-07-11 14:17
Proof:
<img width="727" alt="screen shot 2016-07-11 at 7 16 48 am" src="https://cloud.githubusercontent.com/assets/1803684/16733704/80e3551c-4737-11e6-892c-fde7dd9a1b1a.png">

**Comment by lyze** [comment] 2016-07-12 01:39
Works for me too! Closing.

**Closed by lyze** 2016-07-12 01:39 UTC
